export enum TokenType {
    Word,
    Keyword,
    Constant,
    Operator,
    Variable,
    Type,
    Function,
    Punctuation,
    Bracket,
    String,
    Comment,
    Decorator,
    PropertyHolder,
    Escape,
    Subst,
    Regexp,
    Symbol,
    Property,
    Meta,
    Title,
    Tag,
    Attribute,
}

export const typeMap: Record<string, TokenType> = {
    "keyword":                  TokenType.Keyword,
    "built_in":                 TokenType.Function,
    "function":                 TokenType.Function,
    "type":                     TokenType.Type,
    "literal":                  TokenType.Constant,
    "number":                   TokenType.Constant,
    "operator":                 TokenType.Operator,
    "punctuation":              TokenType.Punctuation,

    "variable":                 TokenType.Variable,
    "variable.language":        TokenType.Variable,
    "variable.constant":        TokenType.Constant,

    "title":                    TokenType.Function,
    "title.class":              TokenType.Type,
    "title.class.inherited":    TokenType.Type,
    "title.function":           TokenType.Function,
    "title.function.invoke":    TokenType.Function,
    "params":                   TokenType.Variable,

    "string":                   TokenType.String,
    "char.escape":              TokenType.Escape,
    "subst":                    TokenType.Subst,
    "regexp":                   TokenType.Regexp,
    "symbol":                   TokenType.Symbol,
    "property":                 TokenType.Property,

    "comment":                  TokenType.Comment,
    "doctag":                   TokenType.Comment,

    "meta":                     TokenType.Meta,
    "meta.prompt":              TokenType.Meta,
    "meta keyword":             TokenType.Keyword,
    "meta string":              TokenType.String,

    "section":                  TokenType.Title,
    "tag":                      TokenType.Tag,
    "name":                     TokenType.Tag,
    "attr":                     TokenType.Attribute,
    "attribute":                TokenType.Attribute,

    "bullet":                   TokenType.Punctuation,
    "code":                     TokenType.String,
    "formula":                  TokenType.Regexp,
    "quote":                    TokenType.String,

    "selector-tag":             TokenType.Tag,
    "selector-id":              TokenType.Title,
    "selector-class":           TokenType.Type,
    "selector-attr":            TokenType.Attribute,
    "selector-pseudo":          TokenType.Keyword,

    "template-tag":             TokenType.Tag,
    "template-variable":        TokenType.Variable,
};